objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Priority__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignmentController.cls
public with sharing class AssignmentController {
    @AuraEnabled(cacheable=true)
public static List<Assignment__c> getAssignment(String searchKey, String sortBy,String sortDirection){
    
    String query='SELECT Id,Name,Description__c,DueDate__c,Priority__c,Status__c,Title__c from Assignment__c';
    system.debug('query---'+query);
    if ( searchKey != null && searchKey != '' ) {
        String key = '%' + searchKey + '%';
        query += ' WHERE (Priority__c LIKE :key OR Title__c LIKE :key)';
        //query += ' WHERE Priority__c  LIKE :key';
        //query += 'WHERE Title__c LIKE :key';
    }
    if ( sortBy != null && sortDirection != null ) {
        query += ' ORDER BY ' + sortBy + ' ' + sortDirection;
    }
    return Database.query( query );
}
}