objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Priority__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignmentHandler.cls
public class AssignmentHandler {
    @AuraEnabled
    public static void assignmentInsert(Map<String,Object> assignmnetToInsert){
        Assignment__c assRec = new Assignment__c();
        if(!assignmnetToInsert.isEmpty()){
            for(String key : assignmnetToInsert.keySet()){
                if(key.equals('DueDate__c')){
                    Datetime duedateTime = (DateTime)JSON.deserialize('"' + assignmnetToInsert.get(key)+'"', DateTime.class);
                    assRec.put(key, duedateTime);
                }else{
                    assRec.put(key, assignmnetToInsert.get(key));
                }
            }
            try{
                insert assRec;

            }catch(DMLException ex){
                System.debug(ex.getMessage());
            }
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<Assignment__c> getAssignmentList(){
        return [SELECT Id, Name, Title__c, Priority__c, Status__c, DueDate__c FROM Assignment__c];
    }
}